const tipsData = [
    {
        id: 1,
        festival_id: 1,
        name: "Jenny",
        year_attended: "2022, 2023, 2024",
        tip: "stay at a hotel that has a connected shuttle stop, it'll make your life easy",
    },
    {
        id: 2,
        festival_id: 2,
        name: "Lisa",
        year_attended: "2022, 2023, 2024",
        tip: "maybe stay at an airbnb, they're cheap, and comes with a pool usually in the resort area of Orlando",
    },
    {
        id: 3,
        festival_id: 3,
        name: "Rosie",
        year_attended: "2021, 2022, 2023",
        tip: "if you want to go to after parties, it is better to get a hotel near a subway station in the downtown area rather than near the venue which is up north",
    },
    {
        id: 4,
        festival_id: 4,
        name: "Ellie",
        year_attended: "2024",
        tip: "stay at the Marriott on Champlain, the hotel is connected to the subway station, which makes transit super easy",
    },
    {
        id: 5,
        festival_id: 5,
        name: "Vanessa",
        year_attended: "2023",
        tip: "It's okay to stay a little further away, traffic is easy to navigate, lots of Ubers",
    },
    {
        id: 6,
        festival_id: 7,
        name: "Sandra",
        year_attended: "2022, 2024",
        tip: "It gets cold, remember to dress warm",
    },
    {
        id: 7,
        festival_id: 6,
        name: "Luis",
        year_attended: "2019, 2022, 2024",
        tip: "try to stay within walking distance, it will give you a lot less headache when leaving the venue",
    },
    {
        id: 8,
        festival_id: 8,
        name: "Bruce",
        year_attended: "2023",
        tip: "The Marriott Champlain is the most convenient hotel, it has a connecting subway station which leads straight to the venue",
    },
    {
        id: 9,
        festival_id: 1,
        name: "John Doe",
        year_attended: "2023",
        tip: "Arrive early to avoid the long lines at security checkpoints.",
    },
    {
        id: 10,
        festival_id: 2,
        name: "Jane Smith",
        year_attended: "2022, 2023",
        tip: "Bring comfortable shoes; the venue is large, and you'll do a lot of walking.",
    },
    {
        id: 11,
        festival_id: 3,
        name: "Alice",
        year_attended: "2021, 2022",
        tip: "Don't forget to bring sunscreen and stay hydrated!",
    },
];
export default tipsData;
